test:
  adapter: mysql
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  database: news_test
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  adapter: mysql
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  database: news_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock